#include "picoquic_internal.h"
#include "seahorn/seahorn.h"

/* WARNING : this file is automagically generated. */

#define ASSERT_NONE 0x0
#define ASSERT_PICOQUIC_CONNECTION_ID_T__ID_LEN 0x1
#define ASSERT_PICOQUIC_TP_PREFERRED_ADDRESS_T__IPV4_PORT 0x1
#define ASSERT_PICOQUIC_TP_PREFERRED_ADDRESS_T__IPV6_PORT 0x2
#define ASSERT_PICOQUIC_TP_T__MAX_IDLE_TIMEOUT 0x1
#define ASSERT_PICOQUIC_TP_T__MAX_PACKET_SIZE 0x2
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_DATA 0x4
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_STREAM_DATA_BIDI_LOCAL 0x8
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_STREAM_DATA_BIDI_REMOTE 0x10
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_STREAM_DATA_UNI 0x20
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_STREAMS_BIDI 0x40
#define ASSERT_PICOQUIC_TP_T__INITIAL_MAX_STREAMS_UNI 0x80
#define ASSERT_PICOQUIC_TP_T__ACK_DELAY_EXPONENT 0x100
#define ASSERT_PICOQUIC_TP_T__MAX_ACK_DELAY 0x200
#define ASSERT_PICOQUIC_TP_T__DISABLE_ACTIVE_MIGRATION 0x400
#define ASSERT_PICOQUIC_TP_T__ACTIVE_CONNECTION_ID_LIMIT 0x800
#define ASSERT_PICOQUIC_CNX_T__PROPOSED_VERSION 0x1
#define ASSERT_PICOQUIC_CNX_T__VERSION_INDEX 0x2
#define ASSERT_PICOQUIC_CNX_T__IS_0RTT_ACCEPTED 0x4
#define ASSERT_PICOQUIC_CNX_T__REMOTE_PARAMETERS_RECEIVED 0x8
#define ASSERT_PICOQUIC_CNX_T__CURRENT_SPIN 0x10
#define ASSERT_PICOQUIC_CNX_T__CLIENT_MODE 0x20
#define ASSERT_PICOQUIC_CNX_T__PREV_SPIN 0x40
#define ASSERT_PICOQUIC_CNX_T__SPIN_VEC 0x80
#define ASSERT_PICOQUIC_CNX_T__SPIN_EDGE 0x100
#define ASSERT_PICOQUIC_CNX_T__SPIN_LAST_TRIGGER 0x200
#define ASSERT_PICOQUIC_CNX_T__KEY_PHASE_ENC 0x400
#define ASSERT_PICOQUIC_CNX_T__KEY_PHASE_DEC 0x800
#define ASSERT_PICOQUIC_CNX_T__ZERO_RTT_DATA_ACCEPTED 0x1000
#define ASSERT_PICOQUIC_CNX_T__ONE_RTT_DATA_ACKNOWLEDGED 0x2000
#define ASSERT_PICOQUIC_CNX_T__PROCESSED_TRANSPORT_PARAMETER 0x4000
#define ASSERT_PICOQUIC_CNX_T__MAX_EARLY_DATA_SIZE 0x8000
#define ASSERT_PICOQUIC_CNX_T__START_TIME 0x10000
#define ASSERT_PICOQUIC_CNX_T__APPLICATION_ERROR 0x20000
#define ASSERT_PICOQUIC_CNX_T__LOCAL_ERROR 0x40000
#define ASSERT_PICOQUIC_CNX_T__REMOTE_APPLICATION_ERROR 0x80000
#define ASSERT_PICOQUIC_CNX_T__REMOTE_ERROR 0x100000
#define ASSERT_PICOQUIC_CNX_T__OFFENDING_FRAME_TYPE 0x200000
#define ASSERT_PICOQUIC_CNX_T__RETRY_TOKEN_LENGTH 0x400000
#define ASSERT_PICOQUIC_CNX_T__HANDSHAKE_DONE 0x800000
#define ASSERT_PICOQUIC_CNX_T__HANDSHAKE_DONE_SENT 0x1000000
#define ASSERT_PICOQUIC_CNX_T__HANDSHAKE_DONE_ACKED 0x2000000
#define ASSERT_PICOQUIC_CNX_T__NEXT_WAKE_TIME 0x4000000
#define ASSERT_PICOQUIC_CNX_T__PSK_CIPHER_SUITE_ID 0x8000000
#define ASSERT_PICOQUIC_CNX_T__LATEST_PROGRESS_TIME 0x10000000
#define ASSERT_PICOQUIC_CNX_T__NB_BYTES_QUEUED 0x20000000
#define ASSERT_PICOQUIC_CNX_T__NB_PATH_CHALLENGE_SENT 0x40000000
#define ASSERT_PICOQUIC_CNX_T__NB_PATH_RESPONSE_RECEIVED 0x80000000
#define ASSERT_PICOQUIC_CNX_T__NB_ZERO_RTT_SENT 0x100000000
#define ASSERT_PICOQUIC_CNX_T__NB_ZERO_RTT_ACKED 0x200000000
#define ASSERT_PICOQUIC_CNX_T__NB_RETRANSMISSION_TOTAL 0x400000000
#define ASSERT_PICOQUIC_CNX_T__NB_SPURIOUS 0x800000000
#define ASSERT_PICOQUIC_CNX_T__DATA_SENT 0x1000000000
#define ASSERT_PICOQUIC_CNX_T__DATA_RECEIVED 0x2000000000
#define ASSERT_PICOQUIC_CNX_T__MAXDATA_LOCAL 0x4000000000
#define ASSERT_PICOQUIC_CNX_T__MAXDATA_REMOTE 0x8000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_BIDIR_LOCAL 0x10000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_BIDIR_LOCAL_COMPUTED 0x20000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_UNIDIR_LOCAL 0x40000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_UNIDIR_LOCAL_COMPUTED 0x80000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_BIDIR_REMOTE 0x100000000000
#define ASSERT_PICOQUIC_CNX_T__MAX_STREAM_ID_UNIDIR_REMOTE 0x200000000000
#define ASSERT_PICOQUIC_CNX_T__LAST_VISITED_STREAM_ID 0x400000000000
#define ASSERT_PICOQUIC_CNX_T__LAST_VISITED_PLUGIN_STREAM_ID 0x800000000000
#define ASSERT_PICOQUIC_CNX_T__KEEP_ALIVE_INTERVAL 0x1000000000000
#define ASSERT_PICOQUIC_CNX_T__NB_PATHS 0x2000000000000
#define ASSERT_PICOQUIC_CNX_T__NB_PATH_ALLOC 0x4000000000000
#define ASSERT_PICOQUIC_CNX_T__CORE_RATE 0x8000000000000
#define ASSERT_PICOQUIC_CNX_T__WAKE_NOW 0x10000000000000
#define ASSERT_PICOQUIC_CNX_T__PLUGIN_REQUESTED 0x20000000000000
#define ASSERT_PICOQUIC_CNX_T__PROTOOP_INPUTC 0x40000000000000
#define ASSERT_PICOQUIC_CNX_T__PROTOOP_OUTPUTC_CALLEE 0x80000000000000
#define ASSERT_PICOQUIC_SACK_ITEM_T__START_OF_SACK_RANGE 0x1
#define ASSERT_PICOQUIC_SACK_ITEM_T__END_OF_SACK_RANGE 0x2
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__SEND_SEQUENCE 0x1
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__TIME_STAMP_LARGEST_RECEIVED 0x2
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__HIGHEST_ACK_SENT 0x4
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__HIGHEST_ACK_TIME 0x8
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__ACK_DELAY_LOCAL 0x10
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__LATEST_PROGRESS_TIME 0x20
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__NB_RETRANSMIT 0x40
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__LATEST_RETRANSMIT_TIME 0x80
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__LATEST_RETRANSMIT_CC_NOTIFICATION_TIME 0x100
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__HIGHEST_ACKNOWLEDGED 0x200
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__LATEST_TIME_ACKNOWLEDGED 0x400
#define ASSERT_PICOQUIC_PACKET_CONTEXT_T__ACK_NEEDED 0x800
#define ASSERT_PICOQUIC_PATH_T__PEER_ADDR_LEN 0x1
#define ASSERT_PICOQUIC_PATH_T__LOCAL_ADDR_LEN 0x2
#define ASSERT_PICOQUIC_PATH_T__IF_INDEX_LOCAL 0x4
#define ASSERT_PICOQUIC_PATH_T__CHALLENGE 0x8
#define ASSERT_PICOQUIC_PATH_T__CHALLENGE_TIME 0x10
#define ASSERT_PICOQUIC_PATH_T__CHALLENGE_REPEAT_COUNT 0x20
#define ASSERT_PICOQUIC_PATH_T__MTU_PROBE_SENT 0x40
#define ASSERT_PICOQUIC_PATH_T__CHALLENGE_VERIFIED 0x80
#define ASSERT_PICOQUIC_PATH_T__CHALLENGE_RESPONSE_TO_SEND 0x100
#define ASSERT_PICOQUIC_PATH_T__PING_RECEIVED 0x200
#define ASSERT_PICOQUIC_PATH_T__LAST_BW_ESTIMATE_PATH_LIMITED 0x400
#define ASSERT_PICOQUIC_PATH_T__MAX_ACK_DELAY 0x800
#define ASSERT_PICOQUIC_PATH_T__RTT_SAMPLE 0x1000
#define ASSERT_PICOQUIC_PATH_T__SMOOTHED_RTT 0x2000
#define ASSERT_PICOQUIC_PATH_T__RTT_VARIANT 0x4000
#define ASSERT_PICOQUIC_PATH_T__RETRANSMIT_TIMER 0x8000
#define ASSERT_PICOQUIC_PATH_T__RTT_MIN 0x10000
#define ASSERT_PICOQUIC_PATH_T__MAX_SPURIOUS_RTT 0x20000
#define ASSERT_PICOQUIC_PATH_T__MAX_REORDER_DELAY 0x40000
#define ASSERT_PICOQUIC_PATH_T__MAX_REORDER_GAP 0x80000
#define ASSERT_PICOQUIC_PATH_T__SEND_MTU 0x100000
#define ASSERT_PICOQUIC_PATH_T__SEND_MTU_MAX_TRIED 0x200000
#define ASSERT_PICOQUIC_PATH_T__CWIN 0x400000
#define ASSERT_PICOQUIC_PATH_T__BYTES_IN_TRANSIT 0x800000
#define ASSERT_PICOQUIC_PATH_T__PACING_EVALUATION_TIME 0x1000000
#define ASSERT_PICOQUIC_PATH_T__PACING_BUCKET_NANOSEC 0x2000000
#define ASSERT_PICOQUIC_PATH_T__PACING_BUCKET_MAX 0x4000000
#define ASSERT_PICOQUIC_PATH_T__PACING_PACKET_TIME_NANOSEC 0x8000000
#define ASSERT_PICOQUIC_PATH_T__PACING_PACKET_TIME_MICROSEC 0x10000000
#define ASSERT_PICOQUIC_PATH_T__NB_PKT_SENT 0x20000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED 0x40000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED_LAST 0x80000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED_TIME_LAST 0x100000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED_SENT_LAST 0x200000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED_LIMITED_INDEX 0x400000000
#define ASSERT_PICOQUIC_PATH_T__DELIVERED_LAST_PACKET 0x800000000
#define ASSERT_PICOQUIC_PATH_T__BANDWIDTH_ESTIMATE 0x1000000000
#define ASSERT_PICOQUIC_PATH_T__RECEIVED 0x2000000000
#define ASSERT_PICOQUIC_PATH_T__RECEIVE_RATE_EPOCH 0x4000000000
#define ASSERT_PICOQUIC_PATH_T__RECEIVED_PRIOR 0x8000000000
#define ASSERT_PICOQUIC_PATH_T__RECEIVE_RATE_ESTIMATE 0x10000000000
#define ASSERT_PICOQUIC_PATH_T__RECEIVE_RATE_MAX 0x20000000000
#define ASSERT_PICOQUIC_PACKET_T__SEQUENCE_NUMBER 0x1
#define ASSERT_PICOQUIC_PACKET_T__SEND_TIME 0x2
#define ASSERT_PICOQUIC_PACKET_T__DELIVERED_PRIOR 0x4
#define ASSERT_PICOQUIC_PACKET_T__DELIVERED_TIME_PRIOR 0x8
#define ASSERT_PICOQUIC_PACKET_T__DELIVERED_SENT_PRIOR 0x10
#define ASSERT_PICOQUIC_PACKET_T__LENGTH 0x20
#define ASSERT_PICOQUIC_PACKET_T__SEND_LENGTH 0x40
#define ASSERT_PICOQUIC_PACKET_T__CHECKSUM_OVERHEAD 0x80
#define ASSERT_PICOQUIC_PACKET_T__OFFSET 0x100
#define ASSERT_PICOQUIC_PACKET_T__IS_PURE_ACK 0x200
#define ASSERT_PICOQUIC_PACKET_T__CONTAINS_CRYPTO 0x400
#define ASSERT_PICOQUIC_PACKET_T__IS_CONGESTION_CONTROLLED 0x800
#define ASSERT_PICOQUIC_PACKET_T__HAS_PLUGIN_FRAMES 0x1000
#define ASSERT_PICOQUIC_PACKET_T__IS_MTU_PROBE 0x2000
#define ASSERT_PICOQUIC_PACKET_T__DELIVERED_APP_LIMITED 0x4000
#define ASSERT_PICOQUIC_PACKET_T__HAS_HANDSHAKE_DONE 0x8000
#define ASSERT_PICOQUIC_PACKET_HEADER__PN 0x1
#define ASSERT_PICOQUIC_PACKET_HEADER__VN 0x2
#define ASSERT_PICOQUIC_PACKET_HEADER__OFFSET 0x4
#define ASSERT_PICOQUIC_PACKET_HEADER__PN_OFFSET 0x8
#define ASSERT_PICOQUIC_PACKET_HEADER__PNMASK 0x10
#define ASSERT_PICOQUIC_PACKET_HEADER__PN64 0x20
#define ASSERT_PICOQUIC_PACKET_HEADER__PAYLOAD_LENGTH 0x40
#define ASSERT_PICOQUIC_PACKET_HEADER__VERSION_INDEX 0x80
#define ASSERT_PICOQUIC_PACKET_HEADER__EPOCH 0x100
#define ASSERT_PICOQUIC_PACKET_HEADER__SPIN 0x200
#define ASSERT_PICOQUIC_PACKET_HEADER__SPIN_VEC 0x400
#define ASSERT_PICOQUIC_PACKET_HEADER__HAS_SPIN_BIT 0x800
#define ASSERT_PICOQUIC_PACKET_HEADER__TOKEN_LENGTH 0x1000
#define ASSERT_PICOQUIC_PACKET_HEADER__TOKEN_OFFSET 0x2000

extern void dummy_cp__picoquic_cnx_t(picoquic_cnx_t *src, picoquic_cnx_t *dst);
extern void dummy_cp__picoquic_tp_t(picoquic_tp_t *src, picoquic_tp_t *dst);
extern void dummy_cp__picoquic_connection_id_t(picoquic_connection_id_t *src, picoquic_connection_id_t *dst);
extern void dummy_cp__picoquic_tp_preferred_address_t(picoquic_tp_preferred_address_t *src, picoquic_tp_preferred_address_t *dst);
extern void dummy_cp__picoquic_packet_context_t(picoquic_packet_context_t *src, picoquic_packet_context_t *dst);
extern void dummy_cp__picoquic_sack_item_t(picoquic_sack_item_t *src, picoquic_sack_item_t *dst);
extern void dummy_cp__picoquic_path_t(picoquic_path_t *src, picoquic_path_t *dst);
extern void dummy_cp__picoquic_packet_t(picoquic_packet_t *src, picoquic_packet_t *dst);
extern void dummy_cp__picoquic_packet_header(picoquic_packet_header *src, picoquic_packet_header *dst);
extern uint8_t dummy__uint8_t();
extern uint16_t dummy__uint16_t();
extern uint64_t dummy__uint64_t();
extern unsigned int dummy__unsigned_int();
extern char dummy__char();
extern uint32_t dummy__uint32_t();
extern int dummy__int();
extern size_t dummy__size_t();
extern unsigned long dummy__unsigned_long();
extern int64_t dummy__int64_t();
extern bool dummy__bool();
inline void init__picoquic_connection_id_t(picoquic_connection_id_t *param1);
inline void init__picoquic_tp_preferred_address_t(picoquic_tp_preferred_address_t *param1);
inline void init__picoquic_tp_t(picoquic_tp_t *param1);
inline void init__picoquic_cnx_t(picoquic_cnx_t *param1);
inline void init__picoquic_sack_item_t(picoquic_sack_item_t *param1);
inline void init__picoquic_packet_context_t(picoquic_packet_context_t *param1);
inline void init__picoquic_path_t(picoquic_path_t *param1);
inline void init__picoquic_packet_t(picoquic_packet_t *param1);
inline void init__picoquic_packet_header(picoquic_packet_header *param1);
inline void assume_cp__picoquic_connection_id_t(picoquic_connection_id_t *src, picoquic_connection_id_t *dst);
inline void assume_cp__picoquic_tp_preferred_address_t(picoquic_tp_preferred_address_t *src, picoquic_tp_preferred_address_t *dst);
inline void assume_cp__picoquic_tp_t(picoquic_tp_t *src, picoquic_tp_t *dst);
inline void assume_cp__picoquic_cnx_t(picoquic_cnx_t *src, picoquic_cnx_t *dst);
inline void assume_cp__picoquic_sack_item_t(picoquic_sack_item_t *src, picoquic_sack_item_t *dst);
inline void assume_cp__picoquic_packet_context_t(picoquic_packet_context_t *src, picoquic_packet_context_t *dst);
inline void assume_cp__picoquic_path_t(picoquic_path_t *src, picoquic_path_t *dst);
inline void assume_cp__picoquic_packet_t(picoquic_packet_t *src, picoquic_packet_t *dst);
inline void assume_cp__picoquic_packet_header(picoquic_packet_header *src, picoquic_packet_header *dst);
inline void assert_cp__picoquic_connection_id_t(picoquic_connection_id_t *param1, picoquic_connection_id_t *param2, uint64_t flags);
inline void assert_cp__picoquic_tp_preferred_address_t(picoquic_tp_preferred_address_t *param1, picoquic_tp_preferred_address_t *param2, uint64_t flags);
inline void assert_cp__picoquic_tp_t(picoquic_tp_t *param1, picoquic_tp_t *param2, uint64_t flags);
inline void assert_cp__picoquic_cnx_t(picoquic_cnx_t *param1, picoquic_cnx_t *param2, uint64_t flags);
inline void assert_cp__picoquic_sack_item_t(picoquic_sack_item_t *param1, picoquic_sack_item_t *param2, uint64_t flags);
inline void assert_cp__picoquic_packet_context_t(picoquic_packet_context_t *param1, picoquic_packet_context_t *param2, uint64_t flags);
inline void assert_cp__picoquic_path_t(picoquic_path_t *param1, picoquic_path_t *param2, uint64_t flags);
inline void assert_cp__picoquic_packet_t(picoquic_packet_t *param1, picoquic_packet_t *param2, uint64_t flags);
inline void assert_cp__picoquic_packet_header(picoquic_packet_header *param1, picoquic_packet_header *param2, uint64_t flags);
